### ISSUE TITLE
upgrade.exe doesn't work on Windows10

### ISSUE THREAD

**Issue by Victe221** [openmultiplayer/upgrade#3]
How to run upgrade.exe or any log/debug with? I copied 'upgrade' folder to openmp-server folder and when I try to start it, it just shutdown within 1 second without any informations/logs. So how can I run it?

**Comment by ADRFranklin** [comment]
It's not an application with a GUI, it's a CLI tool, you open cmd.exe or powershell, you navigate to the folder where the .exe is and you invoke it by calling it as such `upgrade.exe` 

Check the readme what you pass to the program

**Comment by Victe221** [comment]
Sure. Now everything is perfect 🍡
